# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-18 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
